### PR TITLE
First Pull-Request: create database & table

### PR DESCRIPTION
**Pull request by Zven94**
### **Vet Clinic**

This use a relational database to create the data structure for a vet clinic. It started with one table complete with data about:

- animals
- animals' owners
- clinic employees
- visits

Apart from building data structure, it have SQL queries to answer specific questions about date.

Files added:

- queries.sql
- data.sql
- schema.sql

agumon_picachu_birth_day
all_neutered
end_with_mon
name_AND_escape_attempts_
not_like_gabumon
scape_attempts_3
weight_kg_between
year_from_2016_to_2019

### CODE REVIEW

**Review by Davidosky007 — CHANGES_REQUESTED** [review]
Hi @Zven94 👋, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
* Table created properly 👍 
* Well written PR 👍 
* Good looking readme 👍 

## Required Changes ♻️
 * As[ required](https://github.com/microverseinc/curriculum-databases/blob/main/db-structure/vet_clinic_create_tables.md#:~:text=Take%20a%20screenshot,Pull%20Request%20description.) kindly Take a screenshot of the results of your queries.
Copy the SQL you used in the previous point into the queries.sql file in the generated repository.
Remember to add the screenshot with the results of your queries to your Pull Request description.
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @davidsoky007 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Zven94** [comment]
@Davidosky007 I already have a folder with the name of the screenshots in the project

**Comment by Davidosky007** [comment]
Kindly add here also to your PR descriptions

**Review by thecodechaser — APPROVED** [review]
## STATUS: APPROVED 🟢

## Hi @Zven94👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## To Highlight 🎉
- Good job with the animals' table. :heavy_check_mark:
- Gitflow is followed. :heavy_check_mark:
- Professional README file. :heavy_check_mark:
- PR has a good title and summary. ✔️



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
